# paper/config/params.yaml
version: 1

random_seed: 42

preprocessing:
  normalize_total_target_sum: 10000
  log1p: true
  store_layers:
    counts: true
    logcounts: true

subsampling:
  method: stratified_per_cluster
  per_dataset:
    pancancer_cd8:
      cluster_key: meta.cluster
      n_per_cluster: 100
      random_seed: 42
    pancancer_cd4:
      cluster_key: meta.cluster
      n_per_cluster: 100
      random_seed: 42
    brca_stromal:
      cluster_key: meta.cluster
      n_per_cluster: 300
      random_seed: 42
    tabula_muris_b:
      cluster_key: cell_ontology_class
      n_per_cluster: 300
      random_seed: 42

ground_truth:
  label_maps:
    pancancer_cd8: label_maps/pancancer_cd8_gt_map.yaml
    pancancer_cd4: label_maps/pancancer_cd4_gt_map.yaml
    brca_stromal: label_maps/brca_stromal_gt_map.yaml
    tabula_muris_b: label_maps/tabula_muris_b_gt_map.yaml
    # visium_oscc: label_maps/visium_oscc_gt_map.yaml
    # xenium_colon: label_maps/xenium_colon_gt_map.yaml

evaluation:
  exclude_ambiguous_labels:
    pancancer_cd8: ["CD8_Other"]
    pancancer_cd4: ["CD4_Other"]
    brca_stromal: ["Fibro_Other"]
    tabula_muris_b: ["B_Other"]
